# Generated by Django 3.2.8 on 2022-07-26 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0006_medicament_quantite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.CharField(max_length=100)),
                ('quantite', models.IntegerField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateField(auto_now=True)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicament.medicament')),
            ],
        ),
    ]
