# Generated by Django 3.2.8 on 2022-07-27 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approvision', '0001_initial'),
        ('medicament', '0008_approvisionnement_date_peremption'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvisionnement',
            name='fournisseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='approvision.fournisseur'),
        ),
        migrations.AlterField(
            model_name='approvisionnement',
            name='medicament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicament.medicament'),
        ),
    ]
