# Generated by Django 3.2.8 on 2022-08-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0010_remove_medicament_numero_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvisionnement',
            name='quantite',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
